# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-16 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200307_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='uv',
        ),
        migrations.AddField(
            model_name='post',
            name='nv',
            field=models.IntegerField(default=0, verbose_name='踩'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='赞'),
        ),
    ]
