# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-16 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200316_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nv',
            new_name='down',
        ),
        migrations.AddField(
            model_name='post',
            name='up',
            field=models.IntegerField(default=0, verbose_name='赞'),
        ),
        migrations.AddField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
