# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-04 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200103_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editor_type',
            field=models.PositiveIntegerField(choices=[(0, 'markdown编辑器'), (1, '常规编辑器')], default=1, verbose_name='编辑器类型'),
        ),
    ]
