# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-04 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile',
            field=models.CharField(blank=True, default='生的伟大，死的光荣！', max_length=255, verbose_name='自述'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='signature',
            field=models.CharField(blank=True, default='主人有点懒，什么都没有留下！', max_length=64, verbose_name='签名'),
        ),
    ]
