# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191222_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='email是否验证'),
        ),
    ]
