# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_is_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
