# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-29 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191229_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default=0, max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
