# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-30 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191229_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile',
            field=models.CharField(blank=True, default='生的伟大，死的光荣！', max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='signature',
            field=models.CharField(blank=True, default='主人有点懒，什么都没有留下！', max_length=64),
        ),
    ]
