# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-30 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191230_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(blank=True, default='还没昵称', max_length=64, verbose_name='昵称'),
        ),
    ]
