# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-02 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200102_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nv',
            field=models.IntegerField(default=0, verbose_name='反对'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='支持'),
        ),
    ]
