# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-16 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200316_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='nv',
            new_name='down',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pv',
            new_name='up',
        ),
    ]
