# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200102_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
    ]
